### ISSUE TITLE
'struct GPIO_TypeDef' has no member named 'BRR'

### ISSUE THREAD

**Issue by jmohin** [ScruffR/PS2Communication#1]
Veryfing code using this library in Particle Build fails with this error:

```
PS2Communication/PS2Communication.h:39:76: error: 'struct GPIO_TypeDef' has no member named 'BRR'
 #define pinLO(_pin)                        (PIN_MAP[_pin].gpio_peripheral->BRR = PIN_MAP[_pin].gpio_pin)
                                                                            ^
```

This error crops up when trying to compile the PS2Communication library on Photon, using peekay's PIN_MAP inline #define fixes.  It also doesn't compile without them.

**Comment by ScruffR** [comment]
I've postponed the Photon port till system firmware 0.4.2+ is available on the cloud build.
This should have happened already, but got pushed back several times.

**Comment by ScruffR** [comment]
Has been ported to Photon a while ago
