### ISSUE TITLE
type of 'state' does not match original declaration [-Werror]

### ISSUE THREAD

**Issue by w5teen** [ScruffR/PS2Communication#2]
Veryfing code using this library in Particle Build fails with this error:

```
PS2Communication/PS2Communication.cpp:47:18: error: type of 'state' does not match original declaration [-Werror]
 volatile uint8_t state = 0
```

**Comment by ScruffR** [comment]
I'll have to look into it.
Are you building for Photon or Core?

**Comment by w5teen** [comment]
ScruffR
I would ignore this problem. I think the cause was that I had a variable declared as volatile int called 'state'. You have a variable called 'state' in PS2Communication and the compiler correctly kicked this out albeit in a not very easy to understand form. I hit the report to github button and then realised what this was all about.
