### ISSUE TITLE
How to compile for arduino nano?

### ISSUE THREAD

**Issue by GitterHubber** [ScruffR/PS2Communication#3]
Are there any changes that need to be done to the code to get it compiling for Arduino Nano, I see that there is a application.cpp and PS2Mouse.ino in the examples folder?

For the Arduino I think I have to use the .ino file but I haven't had much success in compiling for the Arduino Nano.

**Comment by ScruffR** [comment]
Since this was actually written for Particle devices there are some specifics in that lib, but this can be ported to Arduino too.

But you might also want to look at this
https://www.pjrc.com/teensy/td_libs_PS2Keyboard.html

**Comment by GitterHubber** [comment]
Yes! I have come across that but I was specifically looking for a PS2Mouse library since a mouse has lot of commands that can be send from the host to init the PS2 mouse.

On another note I like your library because it's the only true interrupt driver library I have found on the web,  Although I still don't understand why there are lots of Delay() calls (upto to several milliseconds) in the main sketch.

Eventually I got it compiling on the Arduino Nano is Visual Studio using the Arduino addin for Visual Studio. I had to delete some SPARK related code like wifi, cloudConnect() etc and most importantly I had to move all the Mouse Enums into a seperate .h file and include that file in the main sketch. More details of this error are given here http://forum.arduino.cc/index.php?topic=42032.0

However the compiled size is showing around 9KB around 30% of the 32KB memory that ATmega328p has.

Do you have any recommendations for a good interrupt driven PS2 library for the Arduino? 
I checked the link that you provided and it seems that library is interrupt driven, I need to handle multiple keyboard mice and keyboards on a single Arduino and that link mentions that it supports only 1 keyboard, I wonder why?

Thanks again!

**Comment by ScruffR** [comment]
Some years ago I did the same thing for a Teensy 1.0 - I'll try to dig that up

https://www.pjrc.com/teensy/projects.html

Search for vKeyboardMouse_BT

**Comment by GitterHubber** [comment]
Thanks for the reference but the project files seems to be missing from that page it only has an image and introduction.

**Comment by ScruffR** [comment]
I've dug up my old project.
I haven't looked what state it is in, but you can have a look
<del>https://dl.dropboxusercontent.com/u/60050879/PS2Communication.zip</del>
https://www.dropbox.com/s/6rol0ucezldahuv/PS2Communication.zip?dl=0
