### ISSUE TITLE
What is Particle.h?

### ISSUE THREAD

**Issue by vance** [ScruffR/PS2Communication#4]
No documentation about this? What is it and where do I get it?

**Comment by ScruffR** [comment]
If you are familiar with the Particle platform for which this library is meant you'd know.

But you can also look here
https://github.com/spark/firmware/blob/60f703bd4165a292f89124a7e3755e4eb37b1a03/user/inc/Particle.h
https://github.com/spark/firmware/blob/60f703bd4165a292f89124a7e3755e4eb37b1a03/user/inc/application.h
